version: '3.8'

services:

  web:
    build: .
    container_name: flask
    ports:
      - 5004:5000
    volumes:
      - .:/usr/src/app
    environment:
      - FLASK_DEBUG=1
      - FLASK_ENV=development
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
    depends_on:
      - redis

  worker:
    build: .
    container_name: celery
    command: celery --app tasks.celery worker --loglevel=info
    volumes:
      - .:/usr/src/app
    environment:
      - FLASK_DEBUG=1
      - FLASK_ENV=development
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
    depends_on:
      - web
      - redis

  redis:
    image: redis:6-alpine
    container_name: redis